name: Docker Image CI

env:
  APP_NAME: "bobapp"

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
  build:
    needs: login
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build, Tag and upload image
        run: |
          docker build -t $APP_NAME .
          docker tag $APP_NAME ${{ secrets.DOCKER_HUB_USERNAME }}/$APP_NAME:latest
          docker images
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/$APP_NAME:latest
