name: Docker Image CI

env:
  APP_NAME: "bobapp"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          docker build -t $APP_NAME .
          docker tag $APP_NAME ${{ secrets.DOCKER_HUB_USERNAME }}/$APP_NAME:latest

  login:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

  upload:
    needs: login
    runs-on: ubuntu-latest

    steps:
      - name: Upload image
        run: |
          docker push ${{ secrets.DOCKER_HUB_TOKEN }}/$APP_NAME:latest
